[package]
name = "android-credman"
version = "0.1.0"
edition = "2024"
readme = "README.md"

[dependencies]
android-credman-sys = { workspace = true }

[features]
test-shim = ["android-credman-sys/test-shim"]
