[package]
name = "dcapi-dcql"
version = "0.1.0"
edition = "2024"
readme = "README.md"

[dependencies]
android-credman = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
rustc-hash = { workspace = true }
