[package]
name = "dcapi-dcql"
version = "0.1.0"
edition = "2024"
readme = "README.md"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
thiserror = "2.0"
